### ISSUE TITLE
Document Sensor construction and configuration

### ISSUE THREAD

**Issue by ryanneve** [sunny-day-flooding-project/tutorials#2]
Finish sensor Wiki

**Comment by ththelen** [comment]
I would suggest that Tony and Ryan review and add to the gateway and sensor construction/configuration documents that Lauren and I are developing in the Wiki tab. We could use this thread to notify each other when documentation is ready for Tony/Ryan's review.

**Comment by ththelen** [comment]
I have first drafts of the **Sensor Construction** and **Sensor Hardware (OLA Datalogger & Bluetooth Module)** manuals ready to go in the Wiki tab. I would note that the Sensor Hardware manual was written for the old BlueSMiRF module because Tony has not published his instructions for the new BLE module.
